version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: bird_new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw
      MYSQL_PASSWORD: passw
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/mihai/database:/database
      - bird-db-data:/var/lib/mysql
    networks:
      - my_network

  message_service:
    build:
      context: ./MessageService
      dockerfile: Dockerfile
    container_name: message
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/twitter
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: passw
    ports:
      - "8081:8080"
    networks:
      - my_network

  user_service:
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    container_name: user
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ums
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: passw
    ports:
      - "8080:8080"
    networks:
      - my_network

volumes:
  bird-db-data:

networks:
  my_network:
